version: "3.8"
services:
  mongo:
    image: mongo:8.0.13
    container_name: mongo-task-manager
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak-task-manager-api
    ports:
      - "9999:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: >
      start-dev --import-realm
    volumes:
      - ./docker/task-realm.json:/opt/keycloak/data/import/task-realm.json

volumes:
  mongodata:
  keycloak_data:

